* Spotlight Interface for Gnus nnir Method.

This file provides a Gnus nnir interface for MacOS Spotlight.
As of it, you must use MacOS X and Spotlight to be enabled.
You can use this search engine with `nnmh', `nnml', and `nnmaildir'.

** Emacs Setup

In .emacs, you should set as the following. (`gnus-select-method' is
used in the following examples, but you can specify it in
`gnus-secondary-select-methods`, too.)

First of all, you should choose which method to use Spotlight.

: (require 'nnir-est)
: (setq nnir-method-default-engines
:        '((nnmaildir . spotlight)
:          (nnml . spotlight)
:          (nntp . gmane)))

If you are using `nnml', specifying mail directory may be sufficient.

: ;; nnml/nnmh
: (setq gnus-select-method '(nnml ""))
: (setq nnir-spotlight-prefix "/home/john/Mail/")

or

: (setq gnus-select-method '(nnml "" (nnir-spotlight-prefix "/home/john/Mail/")))

or

: ;; nnmaildir
: (setq gnus-select-method '(nnmaildir "" (directory "~/Maildir")))

If `directory' attribute is specified, it will be used for prefix.
Otherwise, `nnir-spotlight-prefix' will be used.

* Query Format

In `gnus-group-make-nnir-group' query, you can specify following
attributes in addition to query word.

- kMDItemTitle== :: Mail Subject
- kMDItemAuthorEmailAddresses== :: Email author addresses
- kMDItemAuthors== :: Email author
- kMDItemRecipientEmailAddresses== :: Email recipients addresses
- kMDItemRecipients== :: Email recipients
